const bookdata = [
    {
      id: "1",
      title: "Karma Bhoomi",
      author: "Munshi Premchand",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "120",
    },
    {
      id: "2",
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "150",
    },
    {
      id: "3",
      title: "1984",
      author: "George Orwell",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "100",
    },
    {
      id: "4",
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "130",
    },
    {
      id: "5",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "110",
    },
    {
      id: "6",
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "140",
    },
    {
      id: "7",
      title: "Brave New World",
      author: "Aldous Huxley",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "125",
    },
    {
      id: "8",
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "180",
    },
    {
      id: "9",
      title: "Moby-Dick",
      author: "Herman Melville",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "170",
    },
    {
      id: "10",
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "160",
    },
    {
      id: "11",
      title: "Frankenstein",
      author: "Mary Shelley",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "115",
    },
    {
      id: "12",
      title: "The Picture of Dorian Gray",
      author: "Oscar Wilde",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "145",
    },
    {
      id: "13",
      title: "Wuthering Heights",
      author: "Emily Bronte",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "135",
    },
    {
      id: "14",
      title: "Jane Eyre",
      author: "Charlotte Bronte",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "125",
    },
    {
      id: "15",
      title: "The Odyssey",
      author: "Homer",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "155",
    },
    {
      id: "16",
      title: "The Count of Monte Cristo",
      author: "Alexandre Dumas",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "165",
    },
    {
      id: "17",
      title: "Don Quixote",
      author: "Miguel de Cervantes",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "175",
    },
    {
      id: "18",
      title: "The Brothers Karamazov",
      author: "Fyodor Dostoevsky",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "185",
    },
    {
      id: "19",
      title: "War and Peace",
      author: "Leo Tolstoy",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "195",
    },
    {
      id: "20",
      title: "Anna Karenina",
      author: "Leo Tolstoy",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "205",
    },
    // Add more entries as needed
  ];

  export default bookdata;